In [26]:
import pandas as pd
import numpy as np

data = pd.read_csv(r'C:\Users\hi\Documents\PROJEK BELAJAR\machine learning\Nutri_Match\data\raw\nutrition_categorized_v2.csv')

features = ["calories", "proteins", "fat", "carbohydrate"]

# Ambil fitur nutrisi
x = data[features]

# Hitung IQR
Q1 = x.quantile(0.25)
Q3 = x.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Deteksi outlier
outlier = (x < lower_bound) | (x > upper_bound)

outlier
data

,id,calories,proteins,fat,carbohydrate,name,image,category_v2,needs_review_v2
0,1,280.0,9.2,28.4,0.0,Abon,https://img-cdn.medkomtek.com/PbrY9X3ignQ8sVuj...,Protein Hewani,False
1,2,513.0,23.7,37.0,21.3,Abon haruwan,https://img-global.cpcdn.com/recipes/cbf330fbd...,Protein Hewani,False
2,3,0.0,0.0,0.2,0.0,Agar-agar,https://res.cloudinary.com/dk0z4ums3/image/upl...,Camilan,False
3,4,45.0,1.1,0.4,10.8,Akar tonjong segar,https://images.tokopedia.net/img/cache/200-squ...,Sayuran,False
4,5,37.0,4.4,0.5,3.8,Aletoge segar,https://nilaigizi.com/assets/images/produk/pro...,Sayuran,False
...,...,...,...,...,...,...,...,...,...
1341,1342,42.0,1.2,0.6,9.3,Wortel Segar,https://www.astronauts.id/blog/wp-content/uplo...,Sayuran,False
1342,1343,37.0,1.0,0.6,8.3,Wortel kukus,https://www.wikihow.com/images_en/thumb/b/bf/S...,Sayuran,False
1343,1344,28.0,0.7,0.5,6.3,Wortel rebus,https://asset-a.grid.id/crop/0x222:594x690/700...,Sayuran,False
1344,1345,254.0,3.0,1.1,58.1,Yangko,https://serikatnews.com/wp-content/uploads/202...,Camilan,False
1345,1346,52.0,3.3,2.5,4.0,Yoghurt,https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-...,Minuman,False

In [27]:
x.isnull().sum()

calories        0
proteins        0
fat             0
carbohydrate    0
dtype: int64

In [28]:

x[x.duplicated()].count()

x = x.drop_duplicates()

x = x[features]
x

      calories  proteins   fat  carbohydrate
0        280.0       9.2  28.4           0.0
1        513.0      23.7  37.0          21.3
2          0.0       0.0   0.2           0.0
3         45.0       1.1   0.4          10.8
4         37.0       4.4   0.5           3.8
...        ...       ...   ...           ...
1341      42.0       1.2   0.6           9.3
1342      37.0       1.0   0.6           8.3
1343      28.0       0.7   0.5           6.3
1344     254.0       3.0   1.1          58.1
1345      52.0       3.3   2.5           4.0

[1276 rows x 4 columns]

In [29]:
x[x.duplicated()].count()

calories        0
proteins        0
fat             0
carbohydrate    0
dtype: int64

In [30]:
data.head()

,id,calories,proteins,fat,carbohydrate,name,image,category_v2,needs_review_v2
0,1,280.0,9.2,28.4,0.0,Abon,https://img-cdn.medkomtek.com/PbrY9X3ignQ8sVuj...,Protein Hewani,False
1,2,513.0,23.7,37.0,21.3,Abon haruwan,https://img-global.cpcdn.com/recipes/cbf330fbd...,Protein Hewani,False
2,3,0.0,0.0,0.2,0.0,Agar-agar,https://res.cloudinary.com/dk0z4ums3/image/upl...,Camilan,False
3,4,45.0,1.1,0.4,10.8,Akar tonjong segar,https://images.tokopedia.net/img/cache/200-squ...,Sayuran,False
4,5,37.0,4.4,0.5,3.8,Aletoge segar,https://nilaigizi.com/assets/images/produk/pro...,Sayuran,False

In [31]:
x.columns

Index(['calories', 'proteins', 'fat', 'carbohydrate'], dtype='str')

In [32]:
outlier_rows = data.loc[
    outlier.any(axis=1),
    ["name", "calories", "proteins", "fat", "carbohydrate"]
]

outlier_rows

                      name  calories  proteins   fat  carbohydrate
0                     Abon     280.0       9.2  28.4           0.0
1             Abon haruwan     513.0      23.7  37.0          21.3
16                   Angsa     354.0      16.4  31.5           0.0
23            Arwan sirsir     277.0       2.4  25.0          10.7
29                    Ayam     302.0      18.2  25.0           0.0
...                    ...       ...       ...   ...           ...
1325    Udang papay mentah     273.0      47.8   3.8          12.5
1327    Ulat sagu panggang     380.0      11.9  30.3          14.9
1328       Ulat sagu segar     241.0       5.8  21.6           5.8
1337                 Wijen     568.0      19.3  51.1          18.1
1340  Worst (sosis daging)     452.0      14.5  42.3           2.3

[222 rows x 5 columns]

In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
print(x_scaled.shape)

(1276, 4)

In [34]:
import joblib

joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

['../models/scaler.pkl']

In [35]:
x_scaled_data = pd.DataFrame(
    x_scaled,
    columns = features,
    index = x.index
)

x_scaled_data.head()

   calories  proteins       fat  carbohydrate
0  0.504387 -0.064746  1.649468     -0.776972
1  1.976453  1.168959  2.325173     -0.117709
2 -1.264618 -0.847510 -0.566218     -0.776972
3 -0.980314 -0.753919 -0.550504     -0.442698
4 -1.030857 -0.473145 -0.542647     -0.659357

In [36]:
print("Jumlah data awal :", len(data))
print("Jumlah data fitur:", len(x))
print("Jumlah data scaled:", len(x_scaled))

Jumlah data awal : 1346
Jumlah data fitur: 1276
Jumlah data scaled: 1276

In [37]:
print("data:", data.shape)
print("x :", x.shape)

data: (1346, 9)
x : (1276, 4)

In [38]:
print(x.shape)
print(x.index[:10])
print(x.index[-10:])

(1276, 4)
Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')
Index([1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345], dtype='int64')

In [39]:
x = data[features].dropna()