In [43]:
import pandas as pd
import numpy as np

data = pd.read_csv(r'C:\Users\hi\Documents\PROJEK BELAJAR\machine learning\Nutri_Match\data\raw\nutrition.csv')

features = ["calories", "proteins", "fat", "carbohydrate"]

# Ambil fitur nutrisi
X = data[features]

# Hitung IQR
Q1 = X.quantile(0.25)
Q3 = X.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Deteksi outlier
outlier = (X < lower_bound) | (X > upper_bound)

outlier
data

,id,calories,proteins,fat,carbohydrate,name,image
0,1,280.0,9.2,28.4,0.0,Abon,https://img-cdn.medkomtek.com/PbrY9X3ignQ8sVuj...
1,2,513.0,23.7,37.0,21.3,Abon haruwan,https://img-global.cpcdn.com/recipes/cbf330fbd...
2,3,0.0,0.0,0.2,0.0,Agar-agar,https://res.cloudinary.com/dk0z4ums3/image/upl...
3,4,45.0,1.1,0.4,10.8,Akar tonjong segar,https://images.tokopedia.net/img/cache/200-squ...
4,5,37.0,4.4,0.5,3.8,Aletoge segar,https://nilaigizi.com/assets/images/produk/pro...
...,...,...,...,...,...,...,...
1341,1342,42.0,1.2,0.6,9.3,Wortel Segar,https://www.astronauts.id/blog/wp-content/uplo...
1342,1343,37.0,1.0,0.6,8.3,Wortel kukus,https://www.wikihow.com/images_en/thumb/b/bf/S...
1343,1344,28.0,0.7,0.5,6.3,Wortel rebus,https://asset-a.grid.id/crop/0x222:594x690/700...
1344,1345,254.0,3.0,1.1,58.1,Yangko,https://serikatnews.com/wp-content/uploads/202...
1345,1346,52.0,3.3,2.5,4.0,Yoghurt,https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-...

In [44]:
x.isnull().sum()

calories        0
proteins        0
fat             0
carbohydrate    0
dtype: int64

In [45]:

x[x.duplicated()].count()

x = x.drop_duplicates()

x = x[features]
x

      calories  proteins   fat  carbohydrate
0        280.0       9.2  28.4           0.0
1        513.0      23.7  37.0          21.3
2          0.0       0.0   0.2           0.0
3         45.0       1.1   0.4          10.8
4         37.0       4.4   0.5           3.8
...        ...       ...   ...           ...
1341      42.0       1.2   0.6           9.3
1342      37.0       1.0   0.6           8.3
1343      28.0       0.7   0.5           6.3
1344     254.0       3.0   1.1          58.1
1345      52.0       3.3   2.5           4.0

[1276 rows x 4 columns]

In [46]:
x[x.duplicated()].count()

calories        0
proteins        0
fat             0
carbohydrate    0
dtype: int64

In [47]:
data.head()

,id,calories,proteins,fat,carbohydrate,name,image
0,1,280.0,9.2,28.4,0.0,Abon,https://img-cdn.medkomtek.com/PbrY9X3ignQ8sVuj...
1,2,513.0,23.7,37.0,21.3,Abon haruwan,https://img-global.cpcdn.com/recipes/cbf330fbd...
2,3,0.0,0.0,0.2,0.0,Agar-agar,https://res.cloudinary.com/dk0z4ums3/image/upl...
3,4,45.0,1.1,0.4,10.8,Akar tonjong segar,https://images.tokopedia.net/img/cache/200-squ...
4,5,37.0,4.4,0.5,3.8,Aletoge segar,https://nilaigizi.com/assets/images/produk/pro...

In [48]:
x.columns

Index(['calories', 'proteins', 'fat', 'carbohydrate'], dtype='str')

In [49]:
outlier_rows = data.loc[
    outlier.any(axis=1),
    ["name", "calories", "proteins", "fat", "carbohydrate"]
]

outlier_rows

                      name  calories  proteins   fat  carbohydrate
0                     Abon     280.0       9.2  28.4           0.0
1             Abon haruwan     513.0      23.7  37.0          21.3
16                   Angsa     354.0      16.4  31.5           0.0
23            Arwan sirsir     277.0       2.4  25.0          10.7
29                    Ayam     302.0      18.2  25.0           0.0
...                    ...       ...       ...   ...           ...
1325    Udang papay mentah     273.0      47.8   3.8          12.5
1327    Ulat sagu panggang     380.0      11.9  30.3          14.9
1328       Ulat sagu segar     241.0       5.8  21.6           5.8
1337                 Wijen     568.0      19.3  51.1          18.1
1340  Worst (sosis daging)     452.0      14.5  42.3           2.3

[222 rows x 5 columns]

In [50]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaler = scaler.fit_transform(x)
x_scaler

array([[ 0.50438739, -0.06474584,  1.64946766, -0.77697172],
       [ 1.97645265,  1.16895919,  2.32517324, -0.11770946],
       [-1.26461808, -0.84751041, -0.56621807, -0.77697172],
       ...,
       [-1.08771754, -0.78795224, -0.54264695, -0.58197866],
       [ 0.34012259, -0.5922611 , -0.4955047 ,  1.02129763],
       [-0.9360885 , -0.56673617, -0.38550612, -0.6531666 ]],
      shape=(1276, 4))