In [4]:
import joblib

knn = joblib.load('C:/Users/hi/Documents/PROJEK BELAJAR/machine learning/Nutri_Match/models/knn_model.pkl')
scaler = joblib.load('C:/Users/hi/Documents/PROJEK BELAJAR/machine learning/Nutri_Match/models/scaler.pkl')

In [5]:
import pandas as pd

df = pd.read_csv("../data/raw/nutrition_categorized_v2.csv")
df

print(df.shape)
print(type(scaler))
print(type(knn))

(1346, 9)
<class 'sklearn.preprocessing._data.StandardScaler'>
<class 'sklearn.neighbors._unsupervised.NearestNeighbors'>

In [6]:
import numpy as np

input_nutrition = np.array([
    [300, 15, 10, 40]
])

input_scaled = scaler.transform(input_nutrition)

distances, indices = knn.kneighbors(input_scaled)
print(indices)
print(distances)

[[ 291  979   90   65  946  756   62  686  621 1033]]
[[0.29514763 0.4607083  0.50994312 0.58811513 0.59092298 0.6073215
  0.62166968 0.62663135 0.6744325  0.69991341]]

C:\Users\hi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [7]:
recommendations = df.iloc[indices[0]].copy()

recommendations['distances'] = distances[0]

recommendations

df.columns

result = recommendations[
    [
        'id',
        'calories',
        'proteins',
        'fat',
        'carbohydrate',
        'name',
        'image',
        'distances'
    ]
]

result

,id,calories,proteins,fat,carbohydrate,name,image,distances
291,292,301.0,14.2,10.9,49.0,Daun salam bubuk,https://nilaigizi.com/assets/images/produk/pro...,0.295148
979,980,275.0,11.6,11.6,30.2,Pepaya lodeh,https://img-global.cpcdn.com/recipes/5355bb65b...,0.460708
90,91,258.0,10.6,9.5,32.5,Beef burger,https://cdn.id9.site/burgerax/media/2020/09/be...,0.509943
65,66,280.0,8.2,10.2,39.0,Bakwan,https://i0.wp.com/resepkoki.id/wp-content/uplo...,0.588115
946,947,288.6,8.3,8.9,44.3,Onde-onde,https://www.masakapahariini.com/wp-content/upl...,0.590923
756,757,340.0,11.0,11.0,54.0,Ketapang,https://cdn0-production-images-kly.akamaized.n...,0.607321
62,63,272.0,8.7,6.7,44.1,Bakpia kue,https://asset.kompas.com/crops/BZ6Z25Y0XcjtoHB...,0.621670
686,687,275.0,12.6,14.8,54.6,Katul Beras,https://cdn.idntimes.com/content-images/post/2...,0.626631
621,622,327.0,16.4,4.3,55.8,Kacang komak segar,https://sendme.co.id/img/1649134785.jpg,0.674433
1033,1034,295.0,7.3,8.5,47.5,Rarawuan,https://1.bp.blogspot.com/-0ER95zwTjoo/YOHlYJO...,0.699913

In [8]:
def recommend_food(calories, proteins, fat, carbohydrate, n=5):
    
    input_nutrition = np.array([
        [calories, proteins, fat, carbohydrate]
    ])
    
    input_scaled = scaler.transform(input_nutrition)
    
    distances, indices = knn.kneighbors(
        input_scaled,
        n_neighbors=n
    )
    
    recommendations = df.iloc[indices[0]].copy()
    
    recommendations['distances'] = distances[0]
    
    return recommendations

recommend_food(300, 15, 10, 40)
recommend_food(200, 10, 5, 25)
recommend_food(500, 25, 20, 60)

C:\Users\hi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\hi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\hi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

,id,calories,proteins,fat,carbohydrate,name,image,category_v2,needs_review_v2,distances
642,643,488.0,25.6,25.6,59.6,Kacang Sukro Putih,https://cdn1.productnation.co/stg/sites/5/5cbf...,Camilan,False,0.417785
809,810,512.0,26.0,26.0,60.4,Kue Tambang,https://asset.kompas.com/crops/x2yGurVUxpP-COx...,Camilan,False,0.451362
635,636,480.0,18.4,19.1,58.5,Kacang negara,https://cdns.klimg.com/merdeka.com/i/w/news/20...,Protein Nabati,False,0.576252
7,8,414.0,26.6,18.3,41.3,Ampas Tahu,https://palpres.disway.id/upload/9e9c1ba592cac...,Protein Nabati,False,0.805957
1043,1044,497.0,17.0,27.6,50.8,Rempeyek kacang uci,https://img-global.cpcdn.com/recipes/a6f9e4ebc...,Camilan,False,0.919140

PENGETESAN

In [9]:
test_inputs = [
    [200, 10, 5, 25],
    [300, 15, 10, 40],
    [500, 25, 20, 60],
    [700, 30, 30, 80]
]

for i, nutrition in enumerate(test_inputs, 1):
    print(f"\n===== TEST {i} =====")
    print(
        f"Input: {nutrition[0]} kcal, "
        f"{nutrition[1]} protein, "
        f"{nutrition[2]} fat, "
        f"{nutrition[3]} carbohydrate"
    )

    result = recommend_food(*nutrition)

    print(
        result[
            ["name", "calories", "proteins",
             "fat", "carbohydrate", "distances"]
        ].to_string(index=False)
    )

===== TEST 1 =====
Input: 200 kcal, 10 protein, 5 fat, 25 carbohydrate
           name  calories  proteins  fat  carbohydrate  distances
Martabak Telur      200.0       8.9  5.1          29.5   0.168026
          Taoco     166.0      10.4  4.9          24.1   0.213254
 Pempek kelesan     211.0      12.3  6.1          26.6   0.226183
          Oncom     187.0      13.0  6.0          22.6   0.285289
   Oncom Kedele     187.0      13.0  6.0          22.6   0.285289

===== TEST 2 =====
Input: 300 kcal, 15 protein, 10 fat, 40 carbohydrate
             name  calories  proteins  fat  carbohydrate  distances
Daun salam  bubuk     301.0      14.2 10.9          49.0   0.295148
     Pepaya lodeh     275.0      11.6 11.6          30.2   0.460708
      Beef burger     258.0      10.6  9.5          32.5   0.509943
           Bakwan     280.0       8.2 10.2          39.0   0.588115
       Onde-onde      288.6       8.3  8.9          44.3   0.590923

===== TEST 3 =====
Input: 500 kcal, 25 protein, 20 fat, 60 carbohydrate
               name  calories  proteins  fat  carbohydrate  distances
Kacang Sukro Putih      488.0      25.6 25.6          59.6   0.417785
       Kue Tambang      512.0      26.0 26.0          60.4   0.451362
      Kacang negara     480.0      18.4 19.1          58.5   0.576252
         Ampas Tahu     414.0      26.6 18.3          41.3   0.805957
Rempeyek kacang uci     497.0      17.0 27.6          50.8   0.919140

===== TEST 4 =====
Input: 700 kcal, 30 protein, 30 fat, 80 carbohydrate
                     name  calories  proteins  fat  carbohydrate  distances
             Kue Tambang      512.0      26.0 26.0          60.4   1.378384
      Kacang Sukro Putih      488.0      25.6 25.6          59.6   1.527704
            Kacang Telur      748.0      20.8 20.8         124.8   1.754204
Keripik tempe abadi telur     529.0      20.8 31.7          40.2   1.802405
               Susu bubuk     513.0      24.6 30.0          36.2   1.837458

C:\Users\hi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\hi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\hi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\hi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [10]:
result["distances"].is_monotonic_increasing

True